env:
  browser: true
  es2021: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module

extends:
  - airbnb-base
  - eslint:recommended
  - prettier
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended

plugins:
  - react
  - prettier
  - import-order-autofix
  - react-hooks
  - '@typescript-eslint'

rules:
  react/jsx-uses-vars: error
  react/prop-types: 'off'
  react/react-in-jsx-scope: 'off'
  react-hooks/exhaustive-deps: 'warn'
  import/prefer-default-export: 'off'
  max-len:
    - 'error'
    - code: 80
  no-nested-ternary: 'off'
  no-underscore-dangle: 'off'
  no-shadow: 'off'
  import/extensions: 'off'
  no-use-before-define: 'off'
  '@typescript-eslint/no-use-before-define':
    - error
  import/no-unresolved: 0
  '@typescript-eslint/explicit-module-boundary-types': 'off'

settings:
  import/resolver:
    alias:
      extensions:
        - '.ts'
        - '.tsx'
